blank_issues_enabled: false
contact_links:
  - name: Documentation 📚
    url: https://https://farfetch.github.io/kafkaflow/docs/
    about: Check out the official docs for answers to common questions
  - name: Questions & discussions 🤔
    url: https://github.com/Farfetch/kafkaflow/discussions
    about: Ask questions, request features & discuss RFCs
  - name: Community Slack 💬
    url: https://join.slack.com/t/kafkaflow/shared_invite/zt-puihrtcl-NnnylPZloAiVlQfsw~RD6Q
    about: Community discussions and support