name: 💡 Feature Request
description: Suggest a new idea
title: '[Feature Request]:'
labels:
  - needs triage
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your request related to a problem you have?
      description: >-
        A description of the problem you are trying to address.
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen. Include any alternative solutions or features you've considered.
    validations:
      required: true
  - type: dropdown
    id: help
    attributes:
      label: Are you able to help bring it to life and contribute with a Pull Request?
      options:
        - 'No'
        - 'Yes'
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.

