// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MessageTypes
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	/// <summary>
	/// A simple log message type as used by this blog post.
	/// </summary>
	public partial class LogMessages1 : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"LogMessages1\",\"namespace\":\"MessageTypes\",\"fields\":[{\"nam" +
				"e\":\"Severity\",\"type\":{\"type\":\"enum\",\"name\":\"LogLevel\",\"namespace\":\"MessageTypes\"" +
				",\"symbols\":[\"None\",\"Verbose\",\"Info\",\"Warning\",\"Error\"]}}]}");
		private MessageTypes.LogLevel _Severity;
		public virtual Schema Schema
		{
			get
			{
				return LogMessages1._SCHEMA;
			}
		}
		public MessageTypes.LogLevel Severity
		{
			get
			{
				return this._Severity;
			}
			set
			{
				this._Severity = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Severity;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Severity = (MessageTypes.LogLevel)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
