// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SchemaRegistry
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	/// <summary>
	/// Enumerates the set of allowable log levels.
	/// </summary>
	public enum LogLevel
	{
		None,
		Verbose,
		Info,
		Warning,
		Error,
	}
}
