name: Build

on:
  pull_request:

  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Commit Lint
        uses: wagoid/commitlint-github-action@master
        with:
          firstParent: false
          failOnWarnings: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Build Client App
        working-directory: ./src/KafkaFlow.Admin.Dashboard/ClientApp
        run: |
          npm install
          npm run lint
          npm update -D
          npm run build:prod

      - name: Build Framework
        run: dotnet build KafkaFlow.sln -c Release

      - name: UnitTest
        run: |
          dotnet test tests/KafkaFlow.UnitTests/KafkaFlow.UnitTests.csproj -c Release --logger "console;verbosity=detailed"

      - name: IntegrationTest
        run: |
          make init_broker
          dotnet test tests/KafkaFlow.IntegrationTests/KafkaFlow.IntegrationTests.csproj -c Release --logger "console;verbosity=detailed"
          make shutdown_broker
